version: '3.9'

services:
  
  db:
    image: postgres
    ports:
      - 5432:5432
    restart: unless-stopped
    shm_size: 128mb
    volumes:
      - lpms_db:/var/lib/postgresql/data
    env_file:
      - path: ./.env
        required: true
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  app:
    build: ./lpms
    restart: always
    depends_on:
      - db
    command: sh -c "python manage.py migrate &&
                    python manage.py collectstatic --noinput &&
                    python manage.py loaddata db_test.json &&
                    gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - lpms_static:/usr/src/app/shared/static
      - lpms_nginx_conf:/usr/src/app/shared/nginx
    expose:
      - 8000
    env_file:
      - path: ./.env
        required: true
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 8080:80
    depends_on:
      - app
    volumes:
      - lpms_static:/shared/static
      - lpms_nginx_conf:/etc/nginx/conf.d/

volumes:
  lpms_db:
  lpms_static:
  lpms_nginx_conf:


