version: '3.9'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    shm_size: 128mb
    volumes:
      - lpms_db:/var/lib/postgresql/data
    env_file:
      - path: ./.env
        required: true
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
  lmslearnpython:
    image: ghcr.io/mmmylnikov/lpms:lp2409
    restart: always
    depends_on:
      - db
    volumes:
      - lpms_static:/usr/src/app/shared/static
      - lpms_media:/usr/src/app/shared/media
    ports:
      - 8000:8000
    env_file:
      - path: ./.env
        required: true
volumes:
  lpms_db:
  lpms_static:
  lpms_media:
