# Generated by Django 5.0.3 on 2024-03-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gh_username',
            field=models.CharField(max_length=64, null=True, verbose_name='GitHub'),
        ),
        migrations.AddField(
            model_name='user',
            name='tg_username',
            field=models.CharField(max_length=64, null=True, verbose_name='Telegram'),
        ),
    ]
