# Generated by Django 5.0.3 on 2024-04-02 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_group_options_alter_user_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Имя')),
                ('full_name', models.CharField(max_length=512, verbose_name='Полное имя')),
                ('url', models.CharField(max_length=1024, verbose_name='URL')),
                ('html_url', models.CharField(max_length=1024, verbose_name='HTML URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Репозиторий',
                'verbose_name_plural': 'Репозитории',
                'ordering': ('-created_at',),
                'get_latest_by': 'created_at',
            },
        ),
    ]
