# Generated by Django 5.0.3 on 2024-04-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_pull'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify',
            field=models.BooleanField(default=False, verbose_name='Присылать уведомления'),
        ),
    ]
