# Generated by Django 5.0.3 on 2024-11-14 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_is_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-is_superuser', '-is_admin', '-is_tutor', '-is_active', 'last_name', 'first_name', 'username'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
