# Generated by Django 5.0.3 on 2024-03-23 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0005_track'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('content', models.TextField(verbose_name='Контент')),
                ('video', models.TextField(max_length=512, verbose_name='Видеоролик')),
                ('slide', models.TextField(max_length=512, verbose_name='Слайд')),
                ('repo', models.TextField(max_length=512, verbose_name='Репозиторий')),
                ('url', models.TextField(max_length=512, verbose_name='Ссылка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.track', verbose_name='Трек')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ('name',),
                'get_latest_by': 'created_at',
            },
        ),
    ]
