# Generated by Django 5.0.3 on 2024-03-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_alter_lesson_repo_alter_lesson_slide_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='repo',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Репозиторий'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='slide',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Слайд'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='url',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Видеоролик'),
        ),
    ]
