# Generated by Django 5.0.3 on 2024-03-23 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_track'),
        ('learn', '0003_alter_lesson_content_alter_lesson_repo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'get_latest_by': 'created_at', 'ordering': ('track', 'created_at', 'name'), 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Контент')),
                ('repo', models.CharField(blank=True, max_length=512, null=True, verbose_name='Репозиторий')),
                ('url', models.CharField(blank=True, max_length=512, null=True, verbose_name='Ссылка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.track', verbose_name='Трек')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ('track', 'created_at', 'name'),
                'get_latest_by': 'created_at',
            },
        ),
    ]
