# Generated by Django 5.0.3 on 2024-03-23 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0005_homework'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='track',
            new_name='user',
        ),
    ]
