# Generated by Django 5.0.3 on 2024-03-24 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_track'),
        ('learn', '0007_alter_homework_options_homework_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Номер')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('challenges', models.ManyToManyField(to='learn.challenge', verbose_name='Задания')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.course', verbose_name='Курс')),
                ('lessons', models.ManyToManyField(to='learn.lesson', verbose_name='Уроки')),
            ],
            options={
                'verbose_name': 'Неделя',
                'verbose_name_plural': 'Недели',
                'ordering': ('course', 'number'),
                'get_latest_by': 'created_at',
            },
        ),
    ]
