# Generated by Django 5.0.3 on 2024-03-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_track'),
        ('learn', '0009_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='enrollments',
            field=models.ManyToManyField(to='course.enrollment', verbose_name='Потоки'),
        ),
    ]
