# Generated by Django 5.0.3 on 2024-03-30 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_track_options_alter_team_students'),
        ('learn', '0010_alter_program_enrollments'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='course.team', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='homework',
            name='week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='learn.week', verbose_name='Неделя'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='status',
            field=models.CharField(choices=[('available', 'Доступно к выполнению'), ('execution', 'Выполнение'), ('review', 'На проверке'), ('correction', 'Требует исправлений'), ('approved', 'Принято')], default='available', max_length=11, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='week',
            name='challenges',
            field=models.ManyToManyField(blank=True, to='learn.challenge', verbose_name='Задания'),
        ),
        migrations.AlterField(
            model_name='week',
            name='lessons',
            field=models.ManyToManyField(blank=True, to='learn.lesson', verbose_name='Уроки'),
        ),
    ]
