# Generated by Django 5.0.3 on 2024-03-30 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_track_options_alter_team_students'),
        ('learn', '0011_homework_team_homework_week_alter_homework_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.team', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='learn.week', verbose_name='Неделя'),
        ),
    ]
