# Generated by Django 5.0.3 on 2024-04-08 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0012_alter_homework_team_alter_homework_week'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='status',
        ),
        migrations.CreateModel(
            name='HomeworkStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Доступно к выполнению'), ('execution', 'Выполнение'), ('review', 'На проверке'), ('correction', 'Требует исправлений'), ('approved', 'Принято')], default='available', max_length=11, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='learn.homework', verbose_name='Таск/Ревью')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_set', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tutor_set', to=settings.AUTH_USER_MODEL, verbose_name='Куратор')),
            ],
            options={
                'verbose_name': 'Статус работы',
                'verbose_name_plural': 'Статусы работ',
                'ordering': ('-created_at',),
                'get_latest_by': 'created_at',
            },
        ),
    ]
