# Generated by Django 5.0.3 on 2024-04-10 12:46

import learn.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0013_remove_homework_status_homeworkstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='сhallenge',
            new_name='challenge',
        ),
        migrations.AlterField(
            model_name='homework',
            name='repo',
            field=models.CharField(blank=True, max_length=512, null=True, validators=[learn.models.HomeworkRepoValidator()], verbose_name='Репозиторий'),
        ),
    ]
