# Generated by Django 5.0.3 on 2024-07-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0014_rename_сhallenge_homework_challenge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
