# Generated by Django 5.0.3 on 2024-07-14 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0016_alter_challenge_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeworkstatus',
            options={'get_latest_by': 'created_at', 'ordering': ('tutor', 'student', '-updated_at'), 'verbose_name': 'Статус работы', 'verbose_name_plural': 'Статусы работ'},
        ),
    ]
