# Generated by Django 5.0.3 on 2024-11-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0017_alter_homeworkstatus_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='tutor_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий куратора'),
        ),
    ]
