# Generated by Django 5.0.3 on 2024-12-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0018_homework_tutor_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='pull_request_policy',
            field=models.CharField(choices=[('OWN_REPO', 'Личный репозиторий'), ('ANY_REPO_EXCEPT_TASK', 'Любой репозиторий, кроме репозитория задания'), ('ANY_REPO', 'Любой репозиторий')], default='OWN_REPO', max_length=32, verbose_name='Политика пулл-реквестов'),
        ),
    ]
