# Generated by Django 5.0.3 on 2024-12-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0019_challenge_pull_request_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='pull_request_policy',
            field=models.CharField(choices=[('own_repo', 'Личный репозиторий'), ('any_repo_except_task', 'Любой репозиторий, кроме репозитория задания'), ('any_repo', 'Любой репозиторий')], default='own_repo', max_length=32, verbose_name='Политика пулл-реквестов'),
        ),
    ]
