# Generated by Django 5.0.3 on 2024-03-22 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Номер')),
                ('start', models.DateTimeField(verbose_name='Старт')),
                ('finish', models.DateTimeField(verbose_name='Финиш')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Поток',
                'verbose_name_plural': 'Потоки',
                'ordering': ('-finish',),
                'get_latest_by': 'finish',
            },
        ),
    ]
