# Generated by Django 5.0.3 on 2024-03-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='finish',
            field=models.DateField(verbose_name='Финиш'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='start',
            field=models.DateField(verbose_name='Старт'),
        ),
    ]
