# Generated by Django 5.0.3 on 2024-03-22 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_enrollment_finish_alter_enrollment_start'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.enrollment', verbose_name='Поток')),
                ('students', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Студенты')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tutor', to=settings.AUTH_USER_MODEL, verbose_name='Куратор')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ('-enrollment',),
                'get_latest_by': 'created_at',
            },
        ),
    ]
