# Generated by Django 5.0.3 on 2024-07-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_track_options_alter_team_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tg_chat',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Телеграм чат'),
        ),
    ]
