# Generated by Django 5.0.3 on 2024-07-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_enrollment_tg_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='tg_chat',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Телеграм чат'),
        ),
    ]
