name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  
      - name: Install requirements
        run: pip install -r lpms/requirements_dev.txt
      - name: Run flake8
        run: make style
  types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  
      - name: Install requirements
        run: pip install -r lpms/requirements_dev.txt
      - name: Run mypy
        run: make types
  test:
    runs-on: ubuntu-latest
    needs: [lint, types]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  
      - name: Install requirements
        run: pip install -r lpms/requirements_dev.txt
      - name: Run tests
        run: make pytest
