name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    env:
      DEBUG: ${{ vars.DEBUG }}
      ALLOWED_HOSTS: ${{ vars.ALLOWED_HOSTS }}
      GITHUB_OAUTH_CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
      GITHUB_OAUTH_SECRET: ${{ secrets.OAUTH_SECRET }}
      GITHUB_OAUTH_REDIRECT_URL: ${{ secrets.OAUTH_REDIRECT_URL }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  
      - name: Install requirements
        run: pip install -r requirements_dev.txt
      - run: cd lpms/
      - run: pwd
      - name: Run flake8
        run: flake8 .
      - run: pwd
      - name: Run mypy
        run: mypy .
